---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: kargo-receiver
  namespace: flux-system
spec:
  type: generic
  secretRef:
    name: webhook-token
    namespace: kargo-demo
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: kargo-deploy
