---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gobg-prod
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: stage/prod
  secretRef:
    name: flux-system
  url: https://github.com/christianh814/kargo-4-flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gobg-prod
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./app/stages/prod
  prune: true
  targetNamespace: gobg-prod
  sourceRef:
    kind: GitRepository
    name: gobg-prod
