---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gobg-uat
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: stage/uat
  secretRef:
    name: flux-system
  url: https://github.com/christianh814/kargo-4-flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gobg-uat
  namespace: flux-system
spec:
  interval: 15s
  path: ./app/stages/uat
  prune: true
  targetNamespace: gobg-uat
  sourceRef:
    kind: GitRepository
    name: gobg-uat
